### PR TITLE
Fix typo and change Target Framework back to 3.5

### PR DESCRIPTION
**Pull request by akyryz**

### CODE REVIEW

**Comment by Eusth** [comment]
Why do you want to change the target framework?

**Comment by akyryz** [comment]
i am getting this error and changing to 3.5 like all the rest fixes it.
The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)

**Comment by akyryz** [comment]
System.Linq Namespace first appears in .NET Framework 3.5

**Comment by Eusth** [comment]
Yes, I know. It seems like I accidentally linked the System.Core.dll from .NET 3.5 in my local build. Thanks for the heads up!

IllusionPlugin.csproj doesn't really need the version pull-up, but I'll merge it anyway. I'm always a little reluctant with the .NET versions because Unity uses a modified version of .NET 2.0 with a few features from 3.5.

**Pull request merged**
